version: '2'
services:
    influxdb:
        image: influxdb:latest
        container_name: "influxdb"
        ports:
            - 8086:8086
        volumes:
            - /d/dockerspace/jmeter+influxdb+grafana/influxdb/data:/var/lib/influxdb2 
            - /d/dockerspace/jmeter+influxdb+grafana/influxdb/config:/etc/influxdb2
        networks: 
            - jmeterg
        
    grafana:
        image: grafana/grafana:latest
        container_name: "grafana"
        networks: 
            - jmeterg
        ports:
            - 3000:3000
        user:
            "472"
networks:
    jmeterg: